// Auto-generated by scripts/build-gallery.py. Do not edit by hand.
window.FOREST_GALLERY_IMAGES = [
  {
    "src": "images/bluebellFSpilot.jpg",
    "caption": "Bluebell FS"
  },
  {
    "src": "images/FSphotopilotbowsaw.jpg",
    "caption": "FS bowsaw"
  },
  {
    "src": "images/FSphotopilotfairyfires.jpg",
    "caption": "FS fairyfires"
  },
  {
    "src": "images/FSphotopilotgroup.jpg",
    "caption": "FS group"
  },
  {
    "src": "images/FSphotopilotgroupcircle.jpg",
    "caption": "FS groupcircle"
  },
  {
    "src": "images/FSphotopilotjourney.jpg",
    "caption": "FS journey"
  },
  {
    "src": "images/FSphotopilotweaving.jpg",
    "caption": "FS weaving"
  },
  {
    "src": "images/FSphotositspotphoto.jpg",
    "caption": "FS sitspot"
  },
  {
    "src": "images/FSWoods.jpeg",
    "caption": "FSWoods"
  },
  {
    "src": "images/playphotoFSpilot.jpg",
    "caption": "Play FS"
  }
];
