from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
IMAGES = ROOT / "images"
OUT = ROOT / "js" / "gallery-data.js"
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}

# Site/brand graphics should not become portfolio photographs.
EXCLUDE_PARTS = {"logo", "icon", "favicon"}


def natural_key(path: Path):
    return [int(p) if p.isdigit() else p.lower() for p in re.split(r"(\d+)", path.name)]


def make_caption(path: Path) -> str:
    """Turn a filename into a readable fallback caption."""
    stem = path.stem
    stem = re.sub(r"(?i)\bfs\b", "Forest School", stem)
    stem = re.sub(r"(?i)forestschool", "Forest School", stem)
    stem = re.sub(r"(?i)photo", " ", stem)
    stem = re.sub(r"(?i)pilot", " ", stem)
    stem = re.sub(r"[-_]+", " ", stem)
    stem = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", stem)
    stem = re.sub(r"\s+", " ", stem).strip()
    if not stem:
        return "Forest School photograph"
    return stem[0].upper() + stem[1:]


photos = []
for path in sorted(IMAGES.rglob("*"), key=natural_key):
    if not path.is_file() or path.suffix.lower() not in EXTENSIONS:
        continue
    lower_name = path.name.lower()
    if any(part in lower_name for part in EXCLUDE_PARTS):
        continue

    photos.append({
        "src": path.relative_to(ROOT).as_posix(),
        "caption": make_caption(path),
    })

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Auto-generated by scripts/build-gallery.py. Do not edit by hand.\n"
    + "window.FOREST_GALLERY_IMAGES = "
    + json.dumps(photos, indent=2, ensure_ascii=False)
    + ";\n",
    encoding="utf-8",
)
print(f"Wrote {len(photos)} gallery images to {OUT.relative_to(ROOT)}")
